# PostgreSQL Credentials - Dev Environment
# =========================================
#
# IMPORTANT: This secret must exist BEFORE installing PostgreSQL via Helm!
#
# Encrypt before committing:
#   sops -e postgresql-secret.yaml > postgresql-secret.enc.yaml
#   rm postgresql-secret.yaml
#
# The 'password' value must match DATABASE_URL in secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
    namespace: votive-dev
type: Opaque
stringData:
    #ENC[AES256_GCM,data:+U2+bGldJvI1cfspCnNJ1UvgRkZ66a9W8FH9vn0s9cvr1lu1Vft04CMrAUsd,iv:pqDUJBATA0ZLBG/bOIECXDvlkRN5ZCFXAApBUUp75QI=,tag:zziQViie951kdXnW6VkD+w==,type:comment]
    #ENC[AES256_GCM,data:w3pkzF6J9K97X5z62rVEFjb6+2R7TVE=,iv:vGkCNY5wu2TUKS2+y5oEL2vHATgK2dcncc6Lm36g1i8=,tag:blycQGKyKHIXgNdDTewkxQ==,type:comment]
    #ENC[AES256_GCM,data:RpzJt/NRdrp71EAxHIJ7dwREHp+S8bqEZ+lbhwUGTVGoJtdXF0kUEpMMJq7a,iv:fSSycaxbeWmXxMtEimSCoapPFJA1UXZTTXHOPVztK88=,tag:U8tLq9V9Q63EpCBbEXd6SA==,type:comment]
    #ENC[AES256_GCM,data:FBS+H++7oWi0vHqHbg0jPIA6D7/JiPdT6mVmEW/FcQWOTMEvj6lzwvAsX12eHeTFfy52xc64Gg==,iv:zqENXc5unuPgS08mg+z7RU1wdrXl9M8stm7tRFphdRo=,tag:ZXKJfcBuWrf2zyC9J1yctw==,type:comment]
    postgres-password: ENC[AES256_GCM,data:Gknp+kHcdahmq2ie2MxqHeUIpPFHhxI/VTJDln/LouiS1TOK9P1gI9S2ZTMln/l6YOkFKBvlUL3a52hXtEEeIg==,iv:bzgBgcwRsOAv4gSb/noQZwoCtEnCDAe5Ctq25LeU3XI=,tag:w79xZNWRUHKcuR/3qljsSw==,type:str]
    #ENC[AES256_GCM,data:lnJW4ojokQDYlQWRqIj1QXRSQY27kxoOGL8PPPmZXdDWdu9v/mBuMr0MLuRY1r/SR3VXHw==,iv:LEva0EQwEWAMqCRuaadqBM5VHa2DFUPHmzx8CmTM4ew=,tag:WabenCkSWidgVeW+Jv79wA==,type:comment]
    #ENC[AES256_GCM,data:KMiHJr2Ftw0+2VKHKecuUKxfpA7oyWYMIS3eA7frbVghnehcSHSPsQXc1QFG,iv:r02+anZQ0GSXxu9SWofVmAa2XvcupBMrV9i7n9pZhNs=,tag:J/VMpXUGhh564SftSy5KxQ==,type:comment]
    password: ENC[AES256_GCM,data:TAdbK0qvXh55jTAAtLhF0s6SZjyYg2HGr4GehUcjIXnwGRAJDu6UzT1ucYttrQDewXYusbEveHOGFkL2jebLgw==,iv:0mAbDnLI8bwKeuhHCIAatjCwKHp/HJIixz2a3bBROiY=,tag:zYl8ANKtEO+AaFjy9kirbg==,type:str]
sops:
    age:
        - recipient: age13zxcwnqhvg9w2fv22recxkkfgl2xy74zsa2748pr2v0a95t8j48q0tezgf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWGdLZXF3eFNSTVVTSXF4
            SHZKK3duYm5pWmorbmd0bVlEM203eHVIdFZjClhqbEc5dU80ZXRtMGZYSUFxRTRH
            MGZBY2pEL1JRUjlZc0x5NVBhQ3F1TkEKLS0tIDZPR3pSMk1GWU9PRTh6TGUyK3Uw
            VVYxZG56Rzdodkk5ME0xQmp3d0hMUkUKzxyR6fQwfd0mXGTYMRtHPtdfuLoa2giS
            6ANBVsSPdAUAFdm0zrS73MUXFr7U7bVHjTYw6arOHfNt+jQKz2xGEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T17:19:46Z"
    mac: ENC[AES256_GCM,data:qI6O5g2h00g5r94GaxTihuPtPIoWVT1Ox8jD6OZFE1HmPRi0ZmFP9hq1lvtmPukRHVUdcQslnHxBLaQAw0bhNcxTbS1QJtVgoYKpKvil0fT8KnyCXkVgylDq9Xv4Wm3lH4bDQ+7RAV9Oib2iXlUuPDbY9wq/5aSWSDpnYAJtfa0=,iv:3r8ZULaPw1TmHh+07pzKxVwHPS3S0IMNcBNhkR79heQ=,tag:z28DjKQz04NH2IF2DOPb3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
